import { AlgorithmType } from '@/types/algorithm';

export interface LeetCodeProblem {
  id: number;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  url: string;
  description: string;
  acceptance: number;
  topics: string[];
}

export interface AlgorithmLeetCodeData {
  [key: string]: LeetCodeProblem[];
}

export const leetcodeDatabase: Record<AlgorithmType, AlgorithmLeetCodeData> = {
  bfs: {
    Easy: [
      {
        id: 101,
        title: 'Binary Tree Level Order Traversal II',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/binary-tree-level-order-traversal-ii/',
        description: 'Return level order traversal of binary tree in reverse',
        acceptance: 72.5,
        topics: ['Tree', 'Queue', 'BFS'],
      },
      {
        id: 102,
        title: 'Symmetric Tree',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/symmetric-tree/',
        description: 'Check if binary tree is symmetric using BFS level order',
        acceptance: 59.8,
        topics: ['Tree', 'BFS'],
      },
      {
        id: 111,
        title: 'Minimum Depth of Binary Tree',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/minimum-depth-of-binary-tree/',
        description: 'Find minimum depth using BFS shortest path',
        acceptance: 40.2,
        topics: ['Tree', 'BFS'],
      },
      {
        id: 559,
        title: 'Maximum Depth of N-ary Tree',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/maximum-depth-of-n-ary-tree/',
        description: 'Find max depth of n-ary tree using BFS',
        acceptance: 81.3,
        topics: ['Tree', 'BFS'],
      },
      {
        id: 733,
        title: 'Flood Fill',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/flood-fill/',
        description: 'Classic flood fill algorithm using BFS',
        acceptance: 57.4,
        topics: ['Array', 'BFS'],
      },
    ],
    Medium: [
      {
        id: 103,
        title: 'Binary Tree Zigzag Level Order Traversal',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/',
        description: 'Level order traversal with alternating left-right direction',
        acceptance: 60.7,
        topics: ['Tree', 'Queue', 'BFS'],
      },
      {
        id: 127,
        title: 'Word Ladder',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/word-ladder/',
        description: 'Shortest path in word graph using BFS',
        acceptance: 44.3,
        topics: ['BFS', 'Graph', 'Shortest Path'],
      },
      {
        id: 200,
        title: 'Number of Islands',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/number-of-islands/',
        description: 'Count connected components in grid using BFS',
        acceptance: 63.9,
        topics: ['Grid', 'BFS', 'DFS'],
      },
      {
        id: 279,
        title: 'Perfect Squares',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/perfect-squares/',
        description: 'Minimum perfect squares sum using BFS shortest path',
        acceptance: 55.8,
        topics: ['BFS', 'DP', 'Math'],
      },
      {
        id: 317,
        title: 'Shortest Distance from All Buildings',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/shortest-distance-from-all-buildings/',
        description: 'Multi-source BFS to find optimal meeting point',
        acceptance: 34.9,
        topics: ['BFS', 'Grid'],
      },
      {
        id: 429,
        title: 'N-ary Tree Level Order Traversal',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/n-ary-tree-level-order-traversal/',
        description: 'BFS level order traversal for n-ary tree',
        acceptance: 78.2,
        topics: ['Tree', 'BFS'],
      },
      {
        id: 505,
        title: 'The Maze II',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/the-maze-ii/',
        description: 'Shortest path in maze using BFS/Dijkstra',
        acceptance: 45.6,
        topics: ['BFS', 'Dijkstra', 'Maze'],
      },
      {
        id: 542,
        title: 'O(1) Matrix',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/01-matrix/',
        description: 'Multi-source BFS to find distance to nearest 0',
        acceptance: 49.3,
        topics: ['BFS', 'Grid', 'Dynamic Programming'],
      },
      {
        id: 690,
        title: 'Employee Importance',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/employee-importance/',
        description: 'Get total importance of employee and subordinates using BFS',
        acceptance: 68.9,
        topics: ['BFS', 'Hash Table'],
      },
      {
        id: 994,
        title: 'Rotting Oranges',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/rotting-oranges/',
        description: 'Multi-source BFS to find minimum time for all oranges to rot',
        acceptance: 54.7,
        topics: ['BFS', 'Multi-source', 'Grid'],
      },
    ],
    Hard: [
      {
        id: 126,
        title: 'Word Ladder II',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/word-ladder-ii/',
        description: 'Find all shortest paths using BFS and DFS',
        acceptance: 27.3,
        topics: ['BFS', 'Backtracking', 'Graph'],
      },
      {
        id: 149,
        title: 'Max Points on a Line',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/max-points-on-a-line/',
        description: 'Use BFS-like approach for geometric problem solving',
        acceptance: 32.8,
        topics: ['Math', 'Hash Table'],
      },
      {
        id: 1293,
        title: 'Shortest Path in a Grid with Obstacles Elimination',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/',
        description: 'BFS with state tracking for obstacle elimination',
        acceptance: 46.3,
        topics: ['BFS', 'Grid', 'State Space'],
      },
      {
        id: 1345,
        title: 'Jump Game IV',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/jump-game-iv/',
        description: 'Shortest jump path using BFS',
        acceptance: 45.8,
        topics: ['BFS', 'Array'],
      },
      {
        id: 1765,
        title: 'Map of Highest Peak',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/map-of-highest-peak/',
        description: 'Multi-source BFS to assign heights',
        acceptance: 61.2,
        topics: ['BFS', 'Grid'],
      },
      {
        id: 1926,
        title: 'Nearest Exit in Maze',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/nearest-exit-in-maze/',
        description: 'BFS to find nearest exit from entrance',
        acceptance: 60.1,
        topics: ['BFS', 'Grid'],
      },
    ],
  },
  dfs: {
    Easy: [
      {
        id: 94,
        title: 'Binary Tree Inorder Traversal',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/binary-tree-inorder-traversal/',
        description: 'DFS in-order traversal of binary tree',
        acceptance: 74.8,
        topics: ['Tree', 'DFS', 'Stack'],
      },
      {
        id: 100,
        title: 'Same Tree',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/same-tree/',
        description: 'Check if two trees are identical using DFS',
        acceptance: 63.9,
        topics: ['Tree', 'DFS'],
      },
      {
        id: 104,
        title: 'Maximum Depth of Binary Tree',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        description: 'Find max depth using DFS recursion',
        acceptance: 78.1,
        topics: ['Tree', 'DFS'],
      },
      {
        id: 543,
        title: 'Diameter of Binary Tree',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/diameter-of-binary-tree/',
        description: 'DFS to find longest path in binary tree',
        acceptance: 60.8,
        topics: ['Tree', 'DFS'],
      },
      {
        id: 617,
        title: 'Merge Two Binary Trees',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/merge-two-binary-trees/',
        description: 'Merge trees using DFS traversal',
        acceptance: 79.3,
        topics: ['Tree', 'DFS'],
      },
    ],
    Medium: [
      {
        id: 98,
        title: 'Validate Binary Search Tree',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/validate-binary-search-tree/',
        description: 'Use DFS to validate BST property',
        acceptance: 35.6,
        topics: ['Tree', 'DFS'],
      },
      {
        id: 105,
        title: 'Construct Binary Tree from Preorder and Inorder Traversal',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
        description: 'Reconstruct tree using DFS traversal patterns',
        acceptance: 58.2,
        topics: ['Tree', 'DFS'],
      },
      {
        id: 113,
        title: 'Path Sum II',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/path-sum-ii/',
        description: 'DFS to find all root-to-leaf paths with target sum',
        acceptance: 54.3,
        topics: ['Tree', 'DFS', 'Backtracking'],
      },
      {
        id: 199,
        title: 'Binary Tree Right Side View',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/binary-tree-right-side-view/',
        description: 'DFS with depth tracking to get right view',
        acceptance: 63.2,
        topics: ['Tree', 'DFS'],
      },
      {
        id: 207,
        title: 'Course Schedule',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/course-schedule/',
        description: 'DFS cycle detection in directed graph',
        acceptance: 50.4,
        topics: ['Graph', 'DFS', 'Topological Sort'],
      },
      {
        id: 210,
        title: 'Course Schedule II',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/course-schedule-ii/',
        description: 'DFS-based topological sort',
        acceptance: 49.3,
        topics: ['Graph', 'DFS', 'Topological Sort'],
      },
      {
        id: 236,
        title: 'Lowest Common Ancestor of Binary Tree',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
        description: 'DFS to find LCA in binary tree',
        acceptance: 60.9,
        topics: ['Tree', 'DFS'],
      },
      {
        id: 257,
        title: 'Binary Tree Paths',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/binary-tree-paths/',
        description: 'DFS to generate all root-to-leaf paths',
        acceptance: 58.7,
        topics: ['Tree', 'DFS'],
      },
      {
        id: 394,
        title: 'Decode String',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/decode-string/',
        description: 'DFS/stack for nested string decoding',
        acceptance: 58.1,
        topics: ['DFS', 'Stack', 'String'],
      },
      {
        id: 437,
        title: 'Path Sum III',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/path-sum-iii/',
        description: 'DFS to find all paths with target sum (any starting node)',
        acceptance: 48.7,
        topics: ['Tree', 'DFS', 'Backtracking'],
      },
    ],
    Hard: [
      {
        id: 124,
        title: 'Binary Tree Maximum Path Sum',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
        description: 'DFS to find maximum path sum in tree',
        acceptance: 42.3,
        topics: ['Tree', 'DFS', 'Dynamic Programming'],
      },
      {
        id: 212,
        title: 'Word Search II',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/word-search-ii/',
        description: 'DFS with Trie for word searching in grid',
        acceptance: 37.5,
        topics: ['DFS', 'Trie', 'Grid'],
      },
      {
        id: 282,
        title: 'Expression Add Operators',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/expression-add-operators/',
        description: 'DFS with backtracking for expression generation',
        acceptance: 38.2,
        topics: ['DFS', 'Backtracking', 'String'],
      },
      {
        id: 329,
        title: 'Longest Increasing Path in Matrix',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/',
        description: 'DFS with memoization for longest path',
        acceptance: 48.1,
        topics: ['DFS', 'Memoization', 'Grid'],
      },
      {
        id: 332,
        title: 'Reconstruct Itinerary',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/reconstruct-itinerary/',
        description: 'DFS-based Eulerian path finding',
        acceptance: 38.9,
        topics: ['DFS', 'Eulerian Path', 'Graph'],
      },
      {
        id: 489,
        title: 'Robot Room Cleaner',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/robot-room-cleaner/',
        description: 'DFS with backtracking for robot movement',
        acceptance: 67.3,
        topics: ['DFS', 'Backtracking'],
      },
    ],
  },
  dijkstra: {
    Easy: [
      {
        id: 1791,
        title: 'Find Center of Star Graph',
        difficulty: 'Easy',
        url: 'https://leetcode.com/problems/find-center-of-star-graph/',
        description: 'Basic graph center finding',
        acceptance: 86.5,
        topics: ['Graph'],
      },
    ],
    Medium: [
      {
        id: 399,
        title: 'Evaluate Division',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/evaluate-division/',
        description: 'Graph shortest path for variable relationships',
        acceptance: 52.8,
        topics: ['Graph', 'DFS', 'Dijkstra'],
      },
      {
        id: 743,
        title: 'Network Delay Time',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/network-delay-time/',
        description: 'Classic Dijkstra - shortest time to reach all nodes',
        acceptance: 54.5,
        topics: ['Dijkstra', 'Graph', 'Shortest Path'],
      },
      {
        id: 787,
        title: 'Cheapest Flights Within K Stops',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
        description: 'Dijkstra with edge constraint on number of stops',
        acceptance: 43.1,
        topics: ['Dijkstra', 'Graph', 'Shortest Path'],
      },
      {
        id: 882,
        title: 'Reachable Nodes In Subdivided Graph',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/reachable-nodes-in-subdivided-graph/',
        description: 'Complex Dijkstra on weighted subdivided graph',
        acceptance: 48.9,
        topics: ['Dijkstra', 'Graph'],
      },
      {
        id: 1334,
        title: 'Find the City With the Smallest Number of Neighbors at a Threshold Distance',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/',
        description: 'Use Dijkstra/Floyd-Warshall to find neighbors within distance',
        acceptance: 58.7,
        topics: ['Dijkstra', 'Shortest Path', 'Graph'],
      },
      {
        id: 1631,
        title: 'Path With Minimum Effort',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/path-with-minimum-effort/',
        description: 'Modified Dijkstra minimizing maximum edge weight',
        acceptance: 54.2,
        topics: ['Dijkstra', 'Graph', 'Binary Search'],
      },
      {
        id: 1976,
        title: 'Number of Ways to Arrive at Destination',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/',
        description: 'Count paths using Dijkstra with modification',
        acceptance: 54.1,
        topics: ['Dijkstra', 'Graph'],
      },
    ],
    Hard: [
      {
        id: 269,
        title: 'Alien Dictionary',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/alien-dictionary/',
        description: 'Topological sort with graph shortest path concepts',
        acceptance: 34.1,
        topics: ['Graph', 'Topological Sort', 'Dijkstra'],
      },
      {
        id: 1514,
        title: 'Path with Maximum Probability',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/path-with-maximum-probability/',
        description: 'Modified Dijkstra for probability maximization',
        acceptance: 57.3,
        topics: ['Dijkstra', 'Graph'],
      },
      {
        id: 1642,
        title: 'Furthest Building You Can Reach',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/furthest-building-you-can-reach/',
        description: 'Dijkstra for resource constrained pathfinding',
        acceptance: 38.3,
        topics: ['Dijkstra', 'Heap', 'Greedy'],
      },
      {
        id: 1697,
        title: 'Checking Existence of Edge Length Limited Paths',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/checking-existence-of-edge-length-limited-paths/',
        description: 'Offline Dijkstra queries with edge weight limits',
        acceptance: 55.6,
        topics: ['Dijkstra', 'Graph', 'Union-Find'],
      },
      {
        id: 2662,
        title: 'Minimum Cost of a Path With Special Roads',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/minimum-cost-of-a-path-with-special-roads/',
        description: 'Dijkstra with special road shortcuts',
        acceptance: 41.2,
        topics: ['Dijkstra', 'Graph'],
      },
    ],
  },
  astar: {
    Easy: [],
    Medium: [
      {
        id: 1091,
        title: 'Shortest Path in Binary Matrix',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/',
        description: 'A* with Manhattan/Euclidean heuristic',
        acceptance: 52.1,
        topics: ['A*', 'BFS', 'Dijkstra', 'Grid'],
      },
      {
        id: 1263,
        title: 'Minimum Moves to Move a Box to Their Target Location',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/minimum-moves-to-move-a-box-to-their-target-location/',
        description: 'A* on complex state space (player + box positions)',
        acceptance: 39.4,
        topics: ['A*', 'BFS', 'State Space'],
      },
      {
        id: 1293,
        title: 'Shortest Path in a Grid with Obstacles Elimination',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/',
        description: 'A* more efficient than BFS with good heuristic',
        acceptance: 46.3,
        topics: ['A*', 'BFS', 'Grid'],
      },
      {
        id: 1368,
        title: 'Minimum Cost to Make at Least One Valid Path in a Grid',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/',
        description: '0-1 Dijkstra/A* variant with directional costs',
        acceptance: 61.2,
        topics: ['A*', '0-1 Dijkstra', 'Grid'],
      },
      {
        id: 1466,
        title: 'Reorder Routes to Make All Paths Lead to the City Zero',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/',
        description: 'A* can optimize reachability checking',
        acceptance: 76.5,
        topics: ['Graph', 'DFS'],
      },
      {
        id: 1654,
        title: 'Minimum Jumps to Reach Home',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/minimum-jumps-to-reach-home/',
        description: 'A* with state space optimization',
        acceptance: 28.8,
        topics: ['A*', 'BFS', 'State Space'],
      },
    ],
    Hard: [
      {
        id: 505,
        title: 'The Maze II',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/the-maze-ii/',
        description: 'A* for optimal maze pathfinding',
        acceptance: 45.6,
        topics: ['A*', 'Dijkstra', 'Maze'],
      },
      {
        id: 1162,
        title: 'As Far from Land as Possible',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/as-far-from-land-as-possible/',
        description: 'Multi-source BFS/A* variant',
        acceptance: 53.8,
        topics: ['Multi-source BFS', 'Grid'],
      },
      {
        id: 1197,
        title: 'Minimum Knight Moves',
        difficulty: 'Medium',
        url: 'https://leetcode.com/problems/minimum-knight-moves/',
        description: 'A* with Chebyshev distance heuristic',
        acceptance: 38.7,
        topics: ['A*', 'BFS', 'Graph'],
      },
      {
        id: 2290,
        title: 'Minimum Obstacle Removal to Reach Corner',
        difficulty: 'Hard',
        url: 'https://leetcode.com/problems/minimum-obstacle-removal-to-reach-corner/',
        description: '0-1 Dijkstra/A* for grid pathfinding with obstacles',
        acceptance: 60.1,
        topics: ['A*', '0-1 Dijkstra', 'Grid'],
      },
    ],
  },
};

export const getDifficultyColor = (difficulty: LeetCodeProblem['difficulty']) => {
  switch (difficulty) {
    case 'Easy':
      return 'bg-green-500/10 text-green-700 dark:text-green-400 border-green-500/20';
    case 'Medium':
      return 'bg-yellow-500/10 text-yellow-700 dark:text-yellow-400 border-yellow-500/20';
    case 'Hard':
      return 'bg-red-500/10 text-red-700 dark:text-red-400 border-red-500/20';
  }
};

export const getDifficultyIcon = (difficulty: LeetCodeProblem['difficulty']) => {
  switch (difficulty) {
    case 'Easy':
      return '🟢';
    case 'Medium':
      return '🟡';
    case 'Hard':
      return '🔴';
  }
};

export const getDifficultyValue = (difficulty: LeetCodeProblem['difficulty']) => {
  switch (difficulty) {
    case 'Easy':
      return 1;
    case 'Medium':
      return 2;
    case 'Hard':
      return 3;
  }
};
